spring:
  application:
    name: user-manager
  config:
    import: optional:file:./config/user-manager.yml
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user-manager
    username: user-manager
    password: user-manager
  flyway:
    enabled: true
    locations: filesystem:migrations

server:
  port: 8083

keycloak:
  admin:
    url: http://localhost:8080
    realm: trading-app    # realm where users are created
    client-id: user-manager-admin
    client-secret: {master_credentials: test}  # from master realm client credentials tab

logging:
  level:
    com.tradingplatform: INFO
    org.springframework.web: INFO
