spring:
  application:
    name: user-manager
  config:
    import: optional:file:./config/user-manager.yml
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/user-manager
    username: user-manager
    password: user-manager
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8083

keycloak:
  admin:
    url: http://localhost:8080
    realm: trading-app    # realm where users are created
    client-id: user-manager-admin
    client-secret: YGUQanrPaqd05GrxYv4IAgKYkuO9K27Q  # from master realm client credentials tab

logging:
  level:
    com.tradingplatform: INFO
    org.springframework.web: INFO
