spring:
  application:
    name: user-manager
  config:
    import: optional:file:./config/user-manager.yml
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user-manager
    username: ${SPRING_DATASOURCE_USERNAME:user-manager}
    password: ${SPRING_DATASOURCE_PASSWORD:user-manager}
  flyway:
    enabled: true
    locations: filesystem:migrations

server:
  port: 8083

keycloak:
  admin:
    url: http://localhost:8080
    realm: trading-app
    client-id: user-manager-admin
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:8S2ymgO9EmQ20Kke2Eulg0Z0c49K0FCy}

logging:
  level:
    com.tradingplatform: INFO
    org.springframework.web: INFO
